site_name: ALP - Algoritmos e Lógica de Programação
site_url: https://thissyalmeida.github.io/materialAula-2026-Fatec/
use_directory_urls: false

theme:
  name: material
  language: pt-BR

  palette:
    - scheme: default
      primary: red
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo escuro

    - scheme: slate
      primary: red
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

# EXTENSÕES IMPORTANTES
markdown_extensions:
  - attr_list
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details

# CSS PERSONALIZADO
extra_css:
  - assets/stylesheets/style.css

nav:
  - Boas-vindas: index.md

  - ALP - Algoritmos e Lógica de Programação:
    - Lógica e Raciocínio:
        - Aula 1 - Lógica e Raciocínio: ALP/aula1-logica-raciocinio.md
        - Exemplos: ALP/.md
    - Conceitos iniciais de Algoritmos:
        - Aula 2 - Formas de Representação de Algoritmos: ALP/aula2-formas-de-representacao-de-algoritmos.md
        - Exemplos: ALP/.md
    - Formas de Representação de Algoritmos:
        - Aula 3: ALP/exercicios-logica-raciocinio.md
        - Exemplos: ALP/.md
    - Linguagem de Programação:
        - Aula 4: ALP/linguagem-programacao.md
        - Exemplos: ALP/.md
    - Linguagem C:
        - Tipos de Dados, Variáveis e Operadores Lógicos:
            - Exercícios: ALP/tipos-variaveis-operadores.md
        - Estruturas de Controle Sequenciais:
            - Exercícios: ALP/estruturas-sequenciais.md
        - Estruturas Condicionais:
            - Exercícios: ALP/estruturas-condicionais.md
        - Estruturas de Repetição:
            - Exercícios: ALP/estruturas-repeticao.md
        - Funções e Procedimentos:
            - Exercícios: ALP/funcoes-procedimentos.md
        - Estruturas Homogêneas - Vetores e Matrizes:
            - Exercícios: ALP/vetores-matrizes.md
    - Linguagem Java:
        - Tipos de Dados, Variáveis e Operadores Lógicos:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas de Controle Sequenciais:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas Condicionais:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas de Repetição:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Funções e Procedimentos:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas Homogêneas - Vetores e Matrizes:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
    - Linguagem Python:
        - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Tipos de Dados, Variáveis e Operadores Lógicos:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas de Controle Sequenciais:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas Condicionais:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas de Repetição:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Funções e Procedimentos:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas Homogêneas - Vetores e Matrizes:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
    - Linguagem JavaScript:
        - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Tipos de Dados, Variáveis e Operadores Lógicos:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas de Controle Sequenciais:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas Condicionais:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas de Repetição:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Funções e Procedimentos:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas Homogêneas - Vetores e Matrizes:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
    - Linguagem Kotlin:
        - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Tipos de Dados, Variáveis e Operadores Lógicos:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas de Controle Sequenciais:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas Condicionais:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas de Repetição:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Funções e Procedimentos:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
        - Estruturas Homogêneas - Vetores e Matrizes:
            - Exercícios: ALP/exercicios-logica-raciocinio.md
  - EST - Estrutura de Dados:
    - Listas, Pilhas e Filas:
        - Exercícios: ED/aula1-introducao.md
    - Árvores e Grafos:
        - Exercícios: ED/index.md


