site_name: ALP - Algoritmos e Lógica de Programação
site_url: https://thissyalmeida.github.io/materialAula-2026-Fatec/
use_directory_urls: false

theme:
  name: material
  language: pt-BR

  palette:
    - scheme: default
      primary: red
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo escuro

    - scheme: slate
      primary: red
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro

# EXTENSÕES IMPORTANTES
markdown_extensions:
  - attr_list
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details

# CSS PERSONALIZADO
extra_css:
  - assets/stylesheets/style.css

nav:
  - Boas-vindas: index.md

  - Lógica e Raciocínio:
      - Aula 1 - Lógica e Raciocínio: ALP/aula1-logica-raciocinio.md
      - Exercícios: ALP/exercicios-logica-raciocinio.md
  - Conceitos iniciais de Algoritmos:
      - Aula 2 - Formas de Representação de Algoritmos: ALP/aula2-formas-de-representacao-de-algoritmos.md
      - Aula 3 - Exercícios: ALP/aula3-exercicios.md
  - Formas de Representação de Algoritmos:
      - Exercícios: ALP/exercicios-logica-raciocinio.md
  - Linguagem de Programação:
      - Exercícios: ALP/linguagem-programacao.md
  - Linguagem C:
      - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Tipos de Dados, Variáveis e Operadores Lógicos:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas de Controle Sequenciais:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas Condicionais:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas de Repetição:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Funções e Procedimentos:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas Homogêneas - Vetores e Matrizes:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
  - Linguagem Java:
      - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Tipos de Dados, Variáveis e Operadores Lógicos:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas de Controle Sequenciais:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas Condicionais:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas de Repetição:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Funções e Procedimentos:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas Homogêneas - Vetores e Matrizes:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
  - Linguagem Python:
      - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Tipos de Dados, Variáveis e Operadores Lógicos:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas de Controle Sequenciais:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas Condicionais:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas de Repetição:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Funções e Procedimentos:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas Homogêneas - Vetores e Matrizes:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
  - Linguagem JavaScript:
      - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Tipos de Dados, Variáveis e Operadores Lógicos:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas de Controle Sequenciais:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas Condicionais:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas de Repetição:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Funções e Procedimentos:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas Homogêneas - Vetores e Matrizes:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
  - Linguagem Kotlin:
      - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Tipos de Dados, Variáveis e Operadores Lógicos:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas de Controle Sequenciais:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas Condicionais:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas de Repetição:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Funções e Procedimentos:
          - Exercícios: ALP/exercicios-logica-raciocinio.md
      - Estruturas Homogêneas - Vetores e Matrizes:
          - Exercícios: ALP/exercicios-logica-raciocinio.md



